// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjgnp06o2X8wE7Z1q-2Ozim96CZPIyM78',
    appId: '1:851355797577:web:b0969d81570fb41fcb5798',
    messagingSenderId: '851355797577',
    projectId: 'reco-task-2db2f',
    authDomain: 'reco-task-2db2f.firebaseapp.com',
    storageBucket: 'reco-task-2db2f.firebasestorage.app',
    measurementId: 'G-NVV04GJTNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqnjuF5aeCGhFYjqPWHg0Rz6k6v8Xf9VI',
    appId: '1:851355797577:android:df2c02c42bada98dcb5798',
    messagingSenderId: '851355797577',
    projectId: 'reco-task-2db2f',
    storageBucket: 'reco-task-2db2f.firebasestorage.app',
  );
}
