# In case you go with Option 1

name: Flutter CI/CD

on:
  push:
    branches: [main, publish_to_firebase]
  pull_request:
    branches: [main, publish_to_firebase]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout My Code 
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flutter 3.32.2
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.2'

      - name: Accept Android Licenses
        run: yes | flutter doctor --android-licenses

      - name: Install Dependencies
        run: flutter pub get

      # Removed test step for now

      - name: Build APK
        run: flutter build apk --release

      - name: List APK Output
        run: ls build/app/outputs/flutter-apk

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          groups: testers
          file: build/app/outputs/flutter-apk/app-release.apk