name: Flutter Build & Upload APK

on:
  push:
    branches: [main, publish_to_firebase]
  pull_request:
    branches: [main, publish_to_firebase]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Java 17 for Android build
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Setup Flutter with the specific version
      - name: Setup Flutter 3.32.2
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.2'

      # Accept Android licenses (required for building)
      - name: Accept Android Licenses
        run: yes | flutter doctor --android-licenses

      # Install Flutter dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Build the release APK
      - name: Build APK (Release)
        run: flutter build apk --release

      # Show the APK file in logs
      - name: List APK Output
        run: ls -l build/app/outputs/flutter-apk/

      # Upload APK to GitHub Artifacts
      - name: Upload APK to GitHub Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
